//Fake Data

export const bikes = [
  {
    id: 1,
    title: "Rockhopper Sport",
    url: "./assets/Rockhopper.webp",
    originalPrice: 750,
    salePrice: 700,
    rating: 5,
  },
  {
    id: 2,
    title: "S-Works Stumpjumper EVO",
    url: "./assets/Stumpjumper.webp",
    originalPrice: 11500,
    salePrice: 6499.99,
    rating: 4.5,
  },
  {
    id: 3,
    title: "Chisel Hardtail",
    url: "./assets/Chisel.webp",
    originalPrice: 1800,
    salePrice: 1349.99,
    rating: 4.5,
  },
  {
    id: 4,
    title: "Fuse 27.5",
    url: "./assets/Fuse.webp",
    originalPrice: 1500,
    salePrice: 949.99,
    rating: 4,
  },
  {
    id: 5,
    title: "S-Works Epic World Cup LTD",
    url: "./assets/worldcupltd.webp",
    originalPrice: 14000,
    salePrice: 12999.99,
    rating: 3.5,
  },
  {
    id: 6,
    title: "STATUS 2 170",
    url: "./assets/status.webp",
    originalPrice: 3500,
    salePrice: null,
    rating: 4,
  },
  {
    id: 7,
    title: "P.1 Trail",
    url: "./assets/p1trail.webp",
    originalPrice: 1000,
    salePrice: 899.99,
    rating: 3,
  },
  {
    id: 8,
    title: "P.2 Trail",
    url: "./assets/p2trail.webp",
    originalPrice: 1500,
    salePrice: 1399.99,
    rating: 3.5,
  },
  {
    id: 9,
    title: "STATUS 2 170 DH",
    url: "./assets/status2.webp",
    originalPrice: 4500,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 10,
    title: "Epic 8 EVO Expert",
    url: "./assets/epic8.webp",
    originalPrice: 7000,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 11,
    title: "Turbo Levo Comp Alloy",
    url: "./assets/turbo.webp",
    originalPrice: 7000,
    salePrice: null,
    rating: 4,
  },
  {
    id: 12,
    title: "Demo Race",
    url: "./assets/demorace.webp",
    originalPrice: 7100,
    salePrice: null,
    rating: 4.5,
  },
];