//Fake Data

export const bikes = [
  {
    id: 1,
    title: "Rockhopper Sport",
    url: "/assets/Rockhopper.webp",
    originalPrice: 750,
    salePrice: 700,
    rating: 5,
    para: "All barn-burner and no benchwarmer, the Rockhopper Sport throws out the playbook when it comes to putting performance points on the board while playing some serious defense on behalf of your wallet. Game-ready with Tektro M275 hydraulic disc brakes, Shimano CUES shifting, and an SR SunTour XCM fork that’s built to hustle, the Rockhopper Sport can tack up the win on any given Sunday—and the rest of the week too for that matter.",
  },
  {
    id: 2,
    title: "S-Works Stumpjumper EVO",
    url: "/assets/Stumpjumper.webp",
    originalPrice: 11500,
    salePrice: 6499.99,
    rating: 4.5,
    para: "What do you get when you pair a 29-inch front wheel with a 27.5-inch rear wheel? The Stumpjumper EVO S-Works, that’s what. With all of the traction and handling benefits of a 29er, but with a smaller, more maneuverable rear wheel, this mullet setup suits a more jibby, playful style. It’s right at home at the bike park, and is a total blast to cut loose with on the trail.",
  },
  {
    id: 3,
    title: "Chisel Hardtail",
    url: "/assets/Chisel.webp",
    originalPrice: 1800,
    salePrice: 1349.99,
    rating: 4.5,
    para: "The all-new Chisel has been purpose-built to tackle modern cross country trails and race courses with the utmost speed. In fact, it shares many of the same modern features as its Epic Hardtail sibling, but in a more budget-friendly package—making it the most efficient and capable alloy hardtail out there.",
  },
  {
    id: 4,
    title: "Fuse 27.5",
    url: "/assets/Fuse.webp",
    originalPrice: 1500,
    salePrice: 949.99,
    rating: 4,
    para: "Calm under pressure, yet deft and precise, the Fuse is an entirely different kind of hardtail. Featuring an all-new longer, lower, and rowdier chassis and 27.5x2.3 wheels and tires, the Fuse 27.5 handles rough, sketchy descents and steep, technical climbs with absolute confidence.",
  },
  {
    id: 5,
    title: "S-Works Epic World Cup LTD",
    url: "/assets/worldcupltd.webp",
    originalPrice: 14000,
    salePrice: 12999.99,
    rating: 3.5,
    para: "As we mark our first half-century, we're celebrating the next 50 years of innovation with the S-Works Epic World Cup Forward 50 LTD. With multiple World Cup wins in its inaugural season, the Epic World Cup immediately established itself as the fastest bike in the world for smoother courses. The Forward 50 LTD comes together in a stunning graphic: gold represents our 50th year, while pink recalls our historic Team Stumpjumper and our commitment to racing with an irreverent, rebellious spirit."
  },
  {
    id: 6,
    title: "STATUS 2 170",
    url: "/assets/status.webp",
    originalPrice: 3500,
    salePrice: null,
    rating: 4,
    para: "STATUS 2 finds the boundaries of mountain bikes and pushes past them. Is it a trail bike? Yes. Park bike? Yep. Cruise to the convenience store and stop for a stealth session on a concrete wall ride? Oh yeah. STATUS 2 is a bike meant to be ridden, however or wherever you ride. Whether you are on the trails, at the bike park, in the streets, or just cutting turns with your friends on a local hill, the STATUS 2 will allow you to ride your way.",
  },
  {
    id: 7,
    title: "P.1 Trail",
    url: "/assets/p1trail.webp",
    originalPrice: 1000,
    salePrice: 899.99,
    rating: 3,
    para: "The all-new P.1 Trail gives young riders a jumping-off point to life on bikes. The lightweight but tough A1 Premium Aluminum frame is designed to take all the hits and keep rolling. The P.1 Trail delivers a simple, high-quality platform that's versatile and packs in category-first features to set them up for limitless progression.",
  },
  {
    id: 8,
    title: "P.2 Trail",
    url: "/assets/p2trail.webp",
    originalPrice: 1500,
    salePrice: 1399.99,
    rating: 3.5,
    para: "The all-new P.2 Trail gives riders a jumping-off point life on bikes. The lightweight but tough A1 Premium Aluminum frame is designed to take all the hits and keep rolling. The P.2 Trail delivers a simple, high-quality platform that's versatile for young riders and packs in category-first features that set them up for limitless progression.",
  },
  {
    id: 9,
    title: "STATUS 2 170 DH",
    url: "/assets/status2.webp",
    originalPrice: 4500,
    salePrice: null,
    rating: 5,
    para: "",
  },
  {
    id: 10,
    title: "Epic 8 EVO Expert",
    url: "/assets/epic8.webp",
    originalPrice: 7000,
    salePrice: null,
    rating: 5,
    para: "STATUS 2 finds the boundaries of mountain bikes and pushes past them. Is it a trail bike? Yes. Park bike? Yep. Cruise to the convenience store and stop for a stealth session on a concrete wall ride? Oh yeah. STATUS 2 is a bike meant to be ridden, however or wherever you ride. Whether you are on the trails, at the bike park, in the streets, or just cutting turns with your friends on a local hill, the STATUS 2 will allow you to ride your way.",
  },
  {
    id: 11,
    title: "Turbo Levo Comp Alloy",
    url: "/assets/turbo.webp",
    originalPrice: 7000,
    salePrice: 5999.99,
    rating: 4,
    para: "The Levo delivers the unbelievable power to ride more trails through an unequaled combination of ride quality, usable power, and ride-anywhere range. It’s the distillation, application, and amplification of a 40-year obsession with creating the world’s best riding mountain bikes. Since its introduction, Levo has set the bar every other e-MTB aims for, and the latest Levo raises that bar again.",
  },
  {
    id: 12,
    title: "Demo Race",
    url: "/assets/demorace.webp",
    originalPrice: 7100,
    salePrice: null,
    rating: 5,
    para: "All-out speed has always been the Demo’s target, and with the Demo Race, it’s no different. Introducing a new flexible wheel-size frame design that allows riders to take advantage of a 29-inch front wheel and a 27.5-inch rear wheel, it’s a special blend that’s long been tested by World Champ Loïc Bruni looking for the perfect balance of traction and maneuverability, but only just green-lighted by the UCI this past year. Not that it stopped the Demo Race from racking up both the Downhill World Championship and overall World Cup titles in its very first season...",
  },
];
